import type { ChatMessage, FilePreview, ModelOption, PendingPermissionAsk, SessionConfig, SessionRuntimeState, SessionSummary, ToolActivity, UploadedFileItem, WorkflowPlan, ActionDetail } from "@/types/app";
export declare function useAgentApp(): {
    sessionId: string;
    sessions: SessionSummary[];
    messages: ChatMessage[];
    uploadedFiles: UploadedFileItem[];
    toolActivities: ToolActivity[];
    workflow: WorkflowPlan;
    selectedPreview: FilePreview;
    runtimeState: SessionRuntimeState;
    inputValue: string;
    isStreaming: boolean;
    availableModels: ModelOption[];
    setInputValue: import("react").Dispatch<import("react").SetStateAction<string>>;
    handleSubmit: () => Promise<void>;
    handleUpload: (file: File) => Promise<void>;
    handlePreviewFile: (fileId: string) => Promise<void>;
    handlePauseResume: () => Promise<void>;
    handleNewSession: () => void;
    handleDeleteSession: (targetSessionId: string) => Promise<void>;
    loadSession: (targetSessionId: string) => Promise<void>;
    toggleThought: (messageId: string, blockId: string) => void;
    updateAction: (callId: string, status: ActionDetail["status"], content: string) => void;
    pendingPermissionAsk: PendingPermissionAsk;
    handleRespondPermissionAsk: (approved: boolean) => Promise<void>;
    closePreview: () => void;
    config: SessionConfig;
    setConfig: (nextConfig: SessionConfig) => Promise<void>;
};
